apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: neurorightspolicies.neuro.pc
spec:
  group: neuro.pc
  scope: Cluster
  names:
    kind: NeuroRightsPolicy
    plural: neurorightspolicies
    singular: neurorightspolicy
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["policyId", "subjectId", "mentalPrivacy"]
              properties:
                policyId:
                  type: string
                subjectId:
                  type: string
                mentalPrivacy:
                  type: object
                  properties:
                    maxRetentionHours:
                      type: integer
                      minimum: 1
                    reconsentIntervalHours:
                      type: integer
                      minimum: 1
                    revocationLatencyMs:
                      type: integer
                      minimum: 0
      subresources:
        status: {}
